'use strict';

/**
 * Error code definitions used in the system
 */
const AUTH_ERRORS = {
    UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
    LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
    REGISTER_FAILED: 'AUTH_REGISTER_FAILED',
    EMAIL_ALREADY_EXISTS: 'AUTH_EMAIL_ALREADY_EXISTS',
    INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
    PASSWORD_RESET_FAILED: 'AUTH_PASSWORD_RESET_FAILED',
    REQUEST_PASSWORD_RESET_FAILED: 'AUTH_REQUEST_PASSWORD_RESET_FAILED',
    RESET_PASSWORD_FAILED: 'AUTH_RESET_PASSWORD_FAILED',
    CHECK_AUTHORIZATION_FAILED: 'AUTH_CHECK_AUTHORIZATION_FAILED',
    NOT_PERMISSIONS: 'AUTH_NOT_PERMISSIONS',
    ACCOUNT_IS_BANNED: 'AUTH_ACCOUNT_IS_BANNED',
    TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
    REFRESH_TOKEN_FAILED: 'AUTH_REFRESH_TOKEN_FAILED',
    LOGOUT_FAILED: 'AUTH_LOGOUT_FAILED',
    CHANGE_PASSWORD_FAILED: 'AUTH_CHANGE_PASSWORD_FAILED',
    CREATE_ACCOUNT_FAILED: 'AUTH_CREATE_ACCOUNT_FAILED',
    VERIFY_OTP_FAILED: 'AUTH_VERIFY_OTP_FAILED',
};

const VALIDATION_ERRORS = {
    VALIDATION_FAILED: 'VAL_VALIDATION_FAILED',
    INVALID_INPUT: 'VAL_INVALID_INPUT',
    MISSING_FIELDS: 'VAL_MISSING_FIELDS',
    INVALID_EMAIL: 'VAL_INVALID_EMAIL',
    INVALID_PASSWORD: 'VAL_INVALID_PASSWORD',
    PASSWORDS_DO_NOT_MATCH: 'VAL_PASSWORDS_DO_NOT_MATCH',
};

const DATA_ERRORS = {
    DATA_NOT_FOUND: 'DATA_NOT_FOUND',
    USER_NOT_FOUND: 'DATA_USER_NOT_FOUND',
    POST_NOT_FOUND: 'DATA_POST_NOT_FOUND',
    COMMENT_NOT_FOUND: 'DATA_COMMENT_NOT_FOUND',
    FRIEND_NOT_FOUND: 'DATA_FRIEND_NOT_FOUND',
    MESSAGE_NOT_FOUND: 'DATA_MESSAGE_NOT_FOUND',
    DATA_CONFLICT: 'DATA_CONFLICT',
};

const USER_ERRORS = {
    UPDATE_PROFILE_FAILED: 'USER_UPDATE_PROFILE_FAILED',
    UPDATE_AVATAR_FAILED: 'USER_UPDATE_AVATAR_FAILED',
    UPDATE_THUMBNAIL_FAILED: 'USER_UPDATE_THUMBNAIL_FAILED',
    GET_PROFILE_FAILED: 'USER_GET_PROFILE_FAILED',
    SEARCH_USER_FAILED: 'USER_SEARCH_FAILED',
    NAME_UPDATE_TIME_LIMIT: 'USER_NAME_UPDATE_TIME_LIMIT',
    SEARCH_USERS_FAILED: 'USER_SEARCH_USERS_FAILED',
};

const POST_ERRORS = {
    CREATE_POST_FAILED: 'POST_CREATE_FAILED',
    UPDATE_POST_FAILED: 'POST_UPDATE_FAILED',
    DELETE_POST_FAILED: 'POST_DELETE_FAILED',
    LIKE_POST_FAILED: 'POST_LIKE_FAILED',
    COMMENT_POST_FAILED: 'POST_COMMENT_FAILED',
};

const FRIEND_ERRORS = {
    ADD_FRIEND_FAILED: 'FRIEND_ADD_FAILED',
    REMOVE_FRIEND_FAILED: 'FRIEND_REMOVE_FAILED',
    SEND_FRIEND_REQUEST_FAILED: 'FRIEND_SEND_REQUEST_FAILED',
    ACCEPT_FRIEND_REQUEST_FAILED: 'FRIEND_ACCEPT_REQUEST_FAILED',
    REJECT_FRIEND_REQUEST_FAILED: 'FRIEND_REJECT_REQUEST_FAILED',
    GET_FRIENDS_LIST_FAILED: 'GET_FRIENDS_LIST_FAILED',
    FRIEND_REQUEST_FAILED: 'FRIEND_REQUEST_FAILED',
    GET_FRIEND_REQUESTS_FAILED: 'GET_FRIEND_REQUESTS_FAILED',
};

const MESSAGE_ERRORS = {
    SEND_MESSAGE_FAILED: 'MSG_SEND_FAILED',
    GET_MESSAGES_FAILED: 'MSG_GET_FAILED',
    GET_CONVERSATIONS_FAILED: 'MSG_GET_CONVERSATIONS_FAILED',
};

const NOTIFICATION_ERRORS = {
    CREATE_NOTIFICATION_FAILED: 'NOTIF_CREATE_FAILED',
    GET_NOTIFICATIONS_FAILED: 'NOTIF_GET_FAILED',
    UPDATE_NOTIFICATION_FAILED: 'NOTIF_UPDATE_FAILED',
};

const SERVER_ERRORS = {
    INTERNAL_SERVER_ERROR: 'SRV_INTERNAL_ERROR',
    SERVICE_UNAVAILABLE: 'SRV_UNAVAILABLE',
    DATABASE_ERROR: 'SRV_DATABASE_ERROR',
    ERR_INTERNAL_SERVER: 'SRV_INTERNAL_ERROR',
};

const REQUEST_ERRORS = {
    BAD_REQUEST: 'REQ_BAD_REQUEST',
    ERR_GET_DATA_FAILED: 'REQ_GET_DATA_FAILED',
    ROUTE_NOT_FOUND: 'REQ_ROUTE_NOT_FOUND',
};

// Combine all error codes into one object
const errorCode = {
    ...AUTH_ERRORS,
    ...VALIDATION_ERRORS,
    ...DATA_ERRORS,
    ...USER_ERRORS,
    ...POST_ERRORS,
    ...FRIEND_ERRORS,
    ...MESSAGE_ERRORS,
    ...NOTIFICATION_ERRORS,
    ...SERVER_ERRORS,
    ...REQUEST_ERRORS,
};

module.exports = {
    // Error codes by category
    AUTH_ERRORS,
    VALIDATION_ERRORS,
    DATA_ERRORS,
    USER_ERRORS,
    POST_ERRORS,
    FRIEND_ERRORS,
    MESSAGE_ERRORS,
    NOTIFICATION_ERRORS,
    SERVER_ERRORS,
    REQUEST_ERRORS,
    
    // Combined collection for backward compatibility
    errorCode
}; 