name: Deploy Backend

on:
  push:
    branches: [ building ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: SSH to EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/chaotok-backend
            git pull origin main
            npm install --production
            pm2 restart chaotok-api || pm2 start src/server.js --name "chaotok-api"
            pm2 save